### PR TITLE
Updated colliders in prefabs by running 'ed_physxUpdatePrefabsWithColliderComponents' command

### PR DESCRIPTION
**Pull request by michalpelka**
Note
This is part of the work to separate PhysX Collider into 2 components: https://github.com/o3de/o3de/pull/14725.
This is currently as draft to avoid submitting it too early.

Reviewers
Please review and approve this draft and once the main change is submitted into o3de I will merge this as well.

Testing
All converted prefabs were processed successfully by the Asset Processor.
Started simulation and drove vacuum robot around with rqt_robot_steering, checked LiDAR data.

### CODE REVIEW

**Review by moraaar — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
Thanks @michalpelka!

**Comment by hultonha** [comment]
(moving to draft to stop the PR being accidentally merged too soon)

**Comment by michalpelka** [comment]
There are a few warnings in main level:
image
I believe it was shown before.

**Comment by moraaar** [comment]
> There are a few warnings in main level: image I believe it was shown before.

Yeah, they look unrelated to PhysX Colliders. But if you want to be 100% sure you could sync back to the normal branches and double check if the warning messages were there before.

**Review by moraaar — APPROVED** [review]

**Comment by moraaar** [comment]
After investigating more about the warning it turns out it was caused by the prefab conversion process, since it didn't have into account fixing prefab's patches so the property paths (stablished by serialization) are wrong. I changed the serialization code of PhysX Mesh to match the old version, that way the property paths remain the same, this is the PR: https://github.com/o3de/o3de/pull/14871

I'll re-run the conversion command and push it here soon.

**Pull request merged**
